export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ADD_PRODUCT_HANDLER = 'ADD_PRODUCT_HANDLER'
export const EDIT_PRODUCT_HANDLER = 'EDIT_PRODUCT_HANDLER'
export const DELETE_PRODUCT_HANDLER = 'DELETE_PRODUCT_HANDLER'

export const UPDATE_CREATE_PRODUCT_DATA = 'UPDATE_CREATE_PRODUCT_DATA'
export const UPDATE_EDIT_PRODUCT_DATA = 'UPDATE_EDIT_PRODUCT_DATA'

export const TOGGLE_CREATE_PRODUCT_MODAL = 'TOGGLE_CREATE_PRODUCT_MODAL'
export const TOGGLE_EDIT_PRODUCT_MODAL = 'TOGGLE_EDIT_PRODUCT_MODAL'